// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9JUhpOMDZSmebZxR3HtF_k-7z0yTBIU',
    appId: '1:437025757756:web:e0f6cbfcfa8bb02cb88139',
    messagingSenderId: '437025757756',
    projectId: 'wowo-1cdc0',
    authDomain: 'wowo-1cdc0.firebaseapp.com',
    storageBucket: 'wowo-1cdc0.firebasestorage.app',
    measurementId: 'G-MKJNTGMVFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkAhu31qr1o4h_p_DuigfSrFWHEfctiY',
    appId: '1:437025757756:android:41857f05802d8387b88139',
    messagingSenderId: '437025757756',
    projectId: 'wowo-1cdc0',
    storageBucket: 'wowo-1cdc0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp9JUhpOMDZSmebZxR3HtF_k-7z0yTBIU',
    appId: '1:437025757756:web:d38bc88fedf5c29ab88139',
    messagingSenderId: '437025757756',
    projectId: 'wowo-1cdc0',
    authDomain: 'wowo-1cdc0.firebaseapp.com',
    storageBucket: 'wowo-1cdc0.firebasestorage.app',
    measurementId: 'G-1VHVSX09NY',
  );
}
